version: "2"
checks:
    method-lines:
        config:
            threshold: 30
exclude_patterns:
    - "bin/"
    - "config/"
    - "nodes_modules/"
    - "public/"
    - "translations/"
    - "var/"
    - "vendor/"
    - "migrations/"
    - "src/DataFixtures/"
